create database Customer_shopping_Behavior;
use Customer_shopping_Behavior;
select * from `Customer Shopping Behavior_cleaned data`;

-- Q1. What is the total revenue generated by male vs. female customers? --

select gender, SUM(purchase_amount) as revenue
from `Customer Shopping Behavior_cleaned data` 
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? --

select customer_id, purchase_amount
from `Customer Shopping Behavior_cleaned data`
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from `Customer Shopping Behavior_cleaned data`);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating), 2) as "Average Product Rating"
from  `Customer Shopping Behavior_cleaned data`
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, ROUND (AVG (purchase_amount),2)
from `Customer Shopping Behavior_cleaned data`
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.

select subscription_status ,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount))as avg_spend,
ROUND(SUM(purchase_amount)) as total_revenue
from `Customer Shopping Behavior_cleaned data`
group by subscription_status
order by total_revenue desc, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT(*) * 100,2) as discount_rate
from  `Customer Shopping Behavior_cleaned data`
group by item_purchased
order by discount_rate desc
 limit 5;
 
 -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from `Customer Shopping Behavior_cleaned data`
where previous_purchases > 5
group by subscription_status
 
-- Q10. What is the revenue contribution of each age group? --

select 
 age_group,
 SUM(purchase_amount) as total_revenue
from `Customer Shopping Behavior_cleaned data`
group by age_group
order by total_revenue desc;